# FROM node:alpine
# WORKDIR '/home/node/app'
# COPY ./package.json ./
# #RUN npm config set unsafe-perm true
# RUN npm install
# COPY . . 
# RUN mkdir node_modules/.cache && chmod -R 777 node_modules/.cache
# # USER node
# CMD ["npm", "run", "start"]

FROM node:alpine

#USER node

#RUN mkdir -p /home/node/app
WORKDIR '/app'

#COPY --chown=node:node package.json .
COPY package.json .

RUN npm install

#COPY --chown=node:node ./ ./
COPY ./ ./

RUN chown -R node:node .
USER node

CMD ["npm", "run", "start"]