sudo: required
services:
  - docker
before_install:
  - openssl aes-256-cbc -K $encrypted_8f2e322189f7_key -iv $encrypted_8f2e322189f7_iv -in credential.json.enc -out credential.json -d
  - curl https://sdk.cloud.google.com | bash > dev/null;
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components update kubectl
  - gcloud auth activate-service-account --key-file service-account.json